os: Visual Studio 2017

environment:
  image: Visual Studio 2017

build:
  verbosity: minimal

build_script:
  - cmd: msbuild /t:restore;build /p:Configuration=Release /m .\RequestCorrelation.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cmd: msbuild /t:pack /p:Configuration=Release /m .\src\RequestCorrelation\RequestCorrelation.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: '**\*.nupkg'
  name: drop